Aqui voy a crear una función bot muy sencilla que me introduzca datos en la base de datos

In [1]:
from selenium import webdriver
import time
from time import sleep
import pandas as pd
from selenium.webdriver.common.keys import Keys

Cargo un listado de los codigos postales y me quedo solo con los de madrid capital.

In [5]:
df= pd.read_csv ("../Data/listacodigos.csv")

In [6]:
madrid=df[7786:7816] # los 20 anteriores los he metido a mano
madrid

      codigopostalid
7786           28027
7787           28028
7788           28029
7789           28030
7790           28031
7791           28032
7792           28033
7793           28034
7794           28035
7795           28036
7796           28037
7797           28038
7798           28039
7799           28040
7800           28041
7801           28042
7802           28043
7803           28044
7804           28045
7805           28046
7806           28047
7807           28048
7808           28049
7809           28050
7810           28051
7811           28052
7812           28053
7813           28054
7814           28055
7815           28220

Y hacemos una función que nos meta un elemento cada 7 min para no quedarnos sin peticiones a Fourscuare

In [7]:
def fill_db (lista):
    driver = webdriver.Chrome()
    driver.implicitly_wait(3)
    driver.get("http://localhost:8501/")
    for item in lista:
        driver.find_element_by_xpath("/html/body/div[1]/div[1]/div/div/div/div/section/div/div[1]/div[6]/div/div[1]/div/input").send_keys(item)
        driver.find_element_by_xpath("/html/body/div[1]/div[1]/div/div/div/div/section/div/div[1]/div[6]/div/div[1]/div/input").send_keys(Keys.ENTER)
        time.sleep(15) #damos tiempo a que se metan los datos
        driver.refresh() #y refrescamos para vaciar el campo
        time.sleep(300)

In [ ]:
fill_db(madrid["codigopostalid"])

7785    28026
7786    28027
7787    28028
7788    28029
7789    28030
7790    28031
7791    28032
7792    28033
7793    28034
7794    28035
7795    28036
7796    28037
7797    28038
7798    28039
7799    28040
7800    28041
7801    28042
7802    28043
7803    28044
7804    28045
7805    28046
7806    28047
7807    28048
7808    28049
7809    28050
7810    28051
7811    28052
7812    28053
7813    28054
7814    28055
7815    28220
Name: codigopostalid, dtype: int64